// AUTO-GENERATED by scripts/gen-migration-manifest.mjs — do not edit.
// Local supabase/migrations manifest baked into the build so the Platform
// Review can diff it against prod's applied list at request time.

export interface LocalMigrationEntry {
  version: string;
  filename: string;
  name: string;
  /** Name this migration is recorded under in the prod history (alias-aware). */
  prodName: string;
}

export interface SchemaProbe {
  kind: "table" | "column";
  table: string;
  column?: string;
}

export const LOCAL_MIGRATIONS: LocalMigrationEntry[] = [
  {
    "version": "0001",
    "filename": "0001_init.sql",
    "name": "0001_init",
    "prodName": "arc_0001_init"
  },
  {
    "version": "0002",
    "filename": "0002_rls.sql",
    "name": "0002_rls",
    "prodName": "arc_0002_rls"
  },
  {
    "version": "0003",
    "filename": "0003_embeddings.sql",
    "name": "0003_embeddings",
    "prodName": "arc_0003_embeddings"
  },
  {
    "version": "20260625000000",
    "filename": "20260625000000_create_ai_telemetry.sql",
    "name": "create_ai_telemetry",
    "prodName": "create_ai_telemetry"
  },
  {
    "version": "20260625010000",
    "filename": "20260625010000_chemical_ghs_intelligence.sql",
    "name": "chemical_ghs_intelligence",
    "prodName": "chemical_ghs_intelligence_bridge"
  },
  {
    "version": "20260625020000",
    "filename": "20260625020000_ghs_hp_code_seed.sql",
    "name": "ghs_hp_code_seed",
    "prodName": "ghs_hp_code_seed"
  },
  {
    "version": "20260625030000",
    "filename": "20260625030000_chemical_storage_buckets.sql",
    "name": "chemical_storage_buckets",
    "prodName": "chemical_storage_buckets"
  },
  {
    "version": "20260625040000",
    "filename": "20260625040000_chemical_ghs_security_hardening.sql",
    "name": "chemical_ghs_security_hardening",
    "prodName": "chemical_ghs_security_hardening"
  },
  {
    "version": "20260625050000",
    "filename": "20260625050000_csp_validation_agent.sql",
    "name": "csp_validation_agent",
    "prodName": "csp_validation_agent"
  },
  {
    "version": "20260625060000",
    "filename": "20260625060000_csp_agent_learning.sql",
    "name": "csp_agent_learning",
    "prodName": "csp_agent_learning"
  },
  {
    "version": "20260625070000",
    "filename": "20260625070000_csp_agent_standup.sql",
    "name": "csp_agent_standup",
    "prodName": "csp_agent_standup"
  },
  {
    "version": "20260625080000",
    "filename": "20260625080000_csp_meeting_agenda.sql",
    "name": "csp_meeting_agenda",
    "prodName": "csp_meeting_agenda"
  },
  {
    "version": "20260625090000",
    "filename": "20260625090000_ehs_validator_spec_phase1.sql",
    "name": "ehs_validator_spec_phase1",
    "prodName": "ehs_validator_spec_phase1"
  },
  {
    "version": "20260625100000",
    "filename": "20260625100000_ehs_validator_spec_phase2.sql",
    "name": "ehs_validator_spec_phase2",
    "prodName": "ehs_validator_spec_phase2"
  },
  {
    "version": "20260625110000",
    "filename": "20260625110000_incident_evidence_fields.sql",
    "name": "incident_evidence_fields",
    "prodName": "incident_evidence_fields"
  },
  {
    "version": "20260625120000",
    "filename": "20260625120000_ehs_validator_spec_gaps.sql",
    "name": "ehs_validator_spec_gaps",
    "prodName": "ehs_validator_spec_gaps"
  },
  {
    "version": "20260625130000",
    "filename": "20260625130000_gateway_agent.sql",
    "name": "gateway_agent",
    "prodName": "gateway_agent"
  },
  {
    "version": "20260625140000",
    "filename": "20260625140000_gateway_agent_phase3.sql",
    "name": "gateway_agent_phase3",
    "prodName": "gateway_agent_phase3"
  },
  {
    "version": "20260625150000",
    "filename": "20260625150000_gateway_agent_profile.sql",
    "name": "gateway_agent_profile",
    "prodName": "gateway_agent_profile"
  },
  {
    "version": "20260626010000",
    "filename": "20260626010000_chemical_inventory_storage_class_ppe.sql",
    "name": "chemical_inventory_storage_class_ppe",
    "prodName": "chemical_inventory_storage_class_ppe"
  },
  {
    "version": "20260627000000",
    "filename": "20260627000000_ops_console.sql",
    "name": "ops_console",
    "prodName": "ops_console"
  },
  {
    "version": "20260627001000",
    "filename": "20260627001000_ops_console_fix_search_path.sql",
    "name": "ops_console_fix_search_path",
    "prodName": "ops_console_fix_search_path"
  },
  {
    "version": "20260627002000",
    "filename": "20260627002000_ops_access_secrets.sql",
    "name": "ops_access_secrets",
    "prodName": "ops_access_secrets"
  },
  {
    "version": "20260627003000",
    "filename": "20260627003000_ops_gate_status.sql",
    "name": "ops_gate_status",
    "prodName": "ops_gate_status"
  },
  {
    "version": "20260627004000",
    "filename": "20260627004000_ops_fix_requests.sql",
    "name": "ops_fix_requests",
    "prodName": "ops_fix_requests"
  },
  {
    "version": "20260627005000",
    "filename": "20260627005000_audit_log.sql",
    "name": "audit_log",
    "prodName": "audit_log"
  },
  {
    "version": "20260627006000",
    "filename": "20260627006000_arc_live_hardening.sql",
    "name": "arc_live_hardening",
    "prodName": "arc_hardening"
  },
  {
    "version": "20260627010000",
    "filename": "20260627010000_dev_command_center.sql",
    "name": "dev_command_center",
    "prodName": "dev_command_center"
  },
  {
    "version": "20260627020000",
    "filename": "20260627020000_dev_tasks_status_lifecycle.sql",
    "name": "dev_tasks_status_lifecycle",
    "prodName": "dev_tasks_status_lifecycle"
  },
  {
    "version": "20260627030000",
    "filename": "20260627030000_dev_tasks_workflow_stages.sql",
    "name": "dev_tasks_workflow_stages",
    "prodName": "dev_tasks_workflow_stages"
  },
  {
    "version": "20260627040000",
    "filename": "20260627040000_dev_file_change_plans_phase7.sql",
    "name": "dev_file_change_plans_phase7",
    "prodName": "dev_file_change_plans_phase7"
  },
  {
    "version": "20260627050000",
    "filename": "20260627050000_dev_artifacts_phase8.sql",
    "name": "dev_artifacts_phase8",
    "prodName": "dev_artifacts_phase8"
  },
  {
    "version": "20260629000000",
    "filename": "20260629000000_dev_review_gates.sql",
    "name": "dev_review_gates",
    "prodName": "dev_review_gates"
  },
  {
    "version": "20260629010000",
    "filename": "20260629010000_dev_approvals_phase10.sql",
    "name": "dev_approvals_phase10",
    "prodName": "dev_approvals_phase10"
  },
  {
    "version": "20260629020000",
    "filename": "20260629020000_dev_github_settings.sql",
    "name": "dev_github_settings",
    "prodName": "dev_github_settings"
  },
  {
    "version": "20260629030000",
    "filename": "20260629030000_dev_applied_changes.sql",
    "name": "dev_applied_changes",
    "prodName": "dev_applied_changes"
  },
  {
    "version": "20260629040000",
    "filename": "20260629040000_dev_deployments_phase13.sql",
    "name": "dev_deployments_phase13",
    "prodName": "dev_deployments_phase13"
  },
  {
    "version": "20260629050000",
    "filename": "20260629050000_dev_learning_loop.sql",
    "name": "dev_learning_loop",
    "prodName": "dev_learning_loop"
  },
  {
    "version": "20260629060000",
    "filename": "20260629060000_dev_review_gates_phase15.sql",
    "name": "dev_review_gates_phase15",
    "prodName": "dev_review_gates_phase15"
  },
  {
    "version": "20260629070000",
    "filename": "20260629070000_dev_test_results_phase16.sql",
    "name": "dev_test_results_phase16",
    "prodName": "dev_test_results_phase16"
  },
  {
    "version": "20260630000000",
    "filename": "20260630000000_ai_findings_rejection_reason.sql",
    "name": "ai_findings_rejection_reason",
    "prodName": "ai_findings_rejection_reason"
  },
  {
    "version": "20260630020000",
    "filename": "20260630020000_waste_profile_composition.sql",
    "name": "waste_profile_composition",
    "prodName": "waste_profile_composition"
  },
  {
    "version": "20260701000000",
    "filename": "20260701000000_chemical_container_capacity.sql",
    "name": "chemical_container_capacity",
    "prodName": "chemical_container_capacity"
  },
  {
    "version": "20260701010000",
    "filename": "20260701010000_chemical_concentration_hazard.sql",
    "name": "chemical_concentration_hazard",
    "prodName": "add_concentration_hazard_columns_to_chemical_inventory"
  },
  {
    "version": "20260702000000",
    "filename": "20260702000000_ai_model_benchmarks.sql",
    "name": "ai_model_benchmarks",
    "prodName": "ai_model_benchmarks"
  },
  {
    "version": "20260702010000",
    "filename": "20260702010000_arc_missing_tables.sql",
    "name": "arc_missing_tables",
    "prodName": "arc_missing_tables"
  },
  {
    "version": "20260702020000",
    "filename": "20260702020000_dev_review_findings.sql",
    "name": "dev_review_findings",
    "prodName": "dev_review_findings"
  },
  {
    "version": "20260706000000",
    "filename": "20260706000000_event_embeddings.sql",
    "name": "event_embeddings",
    "prodName": "event_embeddings"
  },
  {
    "version": "20260706010000",
    "filename": "20260706010000_tenant_module_access.sql",
    "name": "tenant_module_access",
    "prodName": "tenant_module_access"
  },
  {
    "version": "20260707000000",
    "filename": "20260707000000_chemical_container_label.sql",
    "name": "chemical_container_label",
    "prodName": "chemical_container_label"
  },
  {
    "version": "20260707010000",
    "filename": "20260707010000_sds_review_due_date.sql",
    "name": "sds_review_due_date",
    "prodName": "sds_review_due_date"
  },
  {
    "version": "20260707020000",
    "filename": "20260707020000_daily_suggestion_dismiss_rotation.sql",
    "name": "daily_suggestion_dismiss_rotation",
    "prodName": "daily_suggestion_dismiss_rotation"
  },
  {
    "version": "20260707030000",
    "filename": "20260707030000_predictive_risk_engine.sql",
    "name": "predictive_risk_engine",
    "prodName": "predictive_risk_engine"
  },
  {
    "version": "20260707040000",
    "filename": "20260707040000_predictive_risk_go_live_signoff.sql",
    "name": "predictive_risk_go_live_signoff",
    "prodName": "predictive_risk_go_live_signoff"
  },
  {
    "version": "20260710000000",
    "filename": "20260710000000_phase5_learning_loop.sql",
    "name": "phase5_learning_loop",
    "prodName": "phase5_learning_loop"
  },
  {
    "version": "20260710010000",
    "filename": "20260710010000_universal_waste_recycling_tracking.sql",
    "name": "universal_waste_recycling_tracking",
    "prodName": "universal_waste_recycling_tracking"
  },
  {
    "version": "20260710020000",
    "filename": "20260710020000_young_worker_module.sql",
    "name": "young_worker_module",
    "prodName": "young_worker_module"
  },
  {
    "version": "20260710030000",
    "filename": "20260710030000_hazardous_waste_generator_category_and_minimization.sql",
    "name": "hazardous_waste_generator_category_and_minimization",
    "prodName": "hazardous_waste_generator_category_and_minimization"
  },
  {
    "version": "20260710040000",
    "filename": "20260710040000_evacuation_drill_compliance.sql",
    "name": "evacuation_drill_compliance",
    "prodName": "evacuation_drill_compliance"
  }
];

/** Hand-applied migrations verified by probing the live schema instead of the
 * migration history (they have no history record). */
export const SCHEMA_PROBES: Record<string, SchemaProbe> = {
  "create_ai_telemetry": {
    "kind": "table",
    "table": "ai_telemetry"
  },
  "ai_findings_rejection_reason": {
    "kind": "column",
    "table": "ai_findings",
    "column": "rejection_reason"
  },
  "chemical_container_capacity": {
    "kind": "column",
    "table": "chemical_inventory",
    "column": "container_capacity"
  }
};
