"use client";

import { Printer } from "lucide-react";
import type { Audit, AuditFinding } from "@/lib/types";

const TYPE_LABEL: Record<string, string> = {
  internal: "Internal", external: "External", regulatory: "Regulatory",
  supplier: "Supplier", system: "System", process: "Process",
};
const SEV_COLOR: Record<string, string> = {
  critical: "#dc2626", high: "#ea580c", medium: "#d97706", low: "#16a34a",
};
const STATUS_LABEL: Record<string, string> = {
  open: "Open", in_progress: "In Progress", closed: "Closed", accepted_risk: "Accepted Risk",
};

function fmt(s: string | null) {
  if (!s) return "—";
  return new Date(s).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

interface Props {
  audit: Audit;
  findings: AuditFinding[];
  profileMap: Record<string, string>;
  tenantName: string;
}

export function AuditReportButton({ audit, findings, profileMap, tenantName }: Props) {
  function printReport() {
    const w = window.open("", "_blank");
    if (!w) return;

    const rows = findings
      .sort((a, b) => {
        const order = ["critical", "high", "medium", "low"];
        return order.indexOf(a.severity) - order.indexOf(b.severity);
      })
      .map(
        (f) => `
        <tr>
          <td style="max-width:280px">${f.title}<br><small style="color:#64748b">${f.description ?? ""}</small></td>
          <td><span style="color:${SEV_COLOR[f.severity] ?? "#64748b"};font-weight:700;text-transform:capitalize">${f.severity}</span></td>
          <td style="text-transform:capitalize">${f.category.replace(/_/g, " ")}</td>
          <td>${profileMap[f.owner_id ?? ""] ?? "—"}</td>
          <td>${fmt(f.due_date)}</td>
          <td>${STATUS_LABEL[f.status] ?? f.status}</td>
          <td>${f.capa_required ? (f.capa_id ? "Linked" : "Required") : "No"}</td>
        </tr>`,
      )
      .join("");

    const openCount = findings.filter((f) => f.status === "open" || f.status === "in_progress").length;
    const criticalCount = findings.filter((f) => f.severity === "critical" || f.severity === "high").length;

    w.document.write(`<!DOCTYPE html><html><head>
<title>${audit.title} — Audit Report</title>
<style>
  *{box-sizing:border-box}
  body{font-family:system-ui,-apple-system,sans-serif;margin:40px;color:#1e293b;line-height:1.5}
  h1{font-size:22px;font-weight:800;margin:0 0 4px}
  .meta{color:#64748b;font-size:13px;margin:0 0 6px}
  .kpis{display:flex;gap:16px;margin:20px 0;flex-wrap:wrap}
  .kpi{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px 18px;min-width:110px}
  .kpi-num{font-size:28px;font-weight:800;color:#1e293b}
  .kpi-lbl{font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:#94a3b8}
  table{width:100%;border-collapse:collapse;font-size:12px;margin-top:8px}
  th{background:#f8fafc;text-align:left;padding:9px 10px;border-bottom:2px solid #e2e8f0;
     font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#64748b}
  td{padding:9px 10px;border-bottom:1px solid #f1f5f9;vertical-align:top}
  .no-findings{text-align:center;color:#94a3b8;padding:36px;font-size:13px}
  .footer{margin-top:32px;padding-top:14px;border-top:1px solid #e2e8f0;font-size:10px;color:#94a3b8}
  @media print{body{margin:20px}.no-print{display:none}}
</style></head><body>
<h1>${audit.title}</h1>
<div class="meta">${tenantName} &nbsp;·&nbsp; ${TYPE_LABEL[audit.type] ?? audit.type} Audit</div>
<div class="meta">
  Scheduled: ${fmt(audit.scheduled_date)}
  ${audit.completed_date ? ` &nbsp;·&nbsp; Completed: ${fmt(audit.completed_date)}` : ""}
  ${audit.lead_auditor_id ? ` &nbsp;·&nbsp; Lead Auditor: ${profileMap[audit.lead_auditor_id] ?? "—"}` : ""}
</div>
${audit.scope ? `<div class="meta"><em>Scope: ${audit.scope}</em></div>` : ""}

<div class="kpis">
  <div class="kpi"><div class="kpi-num">${findings.length}</div><div class="kpi-lbl">Total Findings</div></div>
  <div class="kpi"><div class="kpi-num" style="color:#dc2626">${criticalCount}</div><div class="kpi-lbl">Critical / High</div></div>
  <div class="kpi"><div class="kpi-num" style="color:#d97706">${openCount}</div><div class="kpi-lbl">Open</div></div>
  <div class="kpi"><div class="kpi-num" style="color:#10b981">${findings.filter(f => f.status === "closed").length}</div><div class="kpi-lbl">Closed</div></div>
</div>

<table>
  <thead><tr>
    <th>Finding</th><th>Severity</th><th>Category</th><th>Owner</th><th>Due Date</th><th>Status</th><th>CAPA</th>
  </tr></thead>
  <tbody>
    ${findings.length > 0 ? rows : '<tr><td colspan="7" class="no-findings">No findings recorded for this audit.</td></tr>'}
  </tbody>
</table>

<div class="footer">
  Generated by SafetyIQ &nbsp;·&nbsp; Reliance Predictive Safety Technologies &nbsp;·&nbsp; ${new Date().toLocaleString()}
</div>
<script>window.onload = function(){ window.print(); }</script>
</body></html>`);
    w.document.close();
  }

  return (
    <button
      onClick={printReport}
      className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50 shrink-0"
    >
      <Printer className="h-3.5 w-3.5" />
      Print Report
    </button>
  );
}
